#!/usr/bin/env python3

import json
import sys

buffer = []

state = {
    'node_ids':[],
    'node_id': '',
    'outgoing_message_id': 0
}

def work(jsondata, state):
    data = json.loads(jsondata)

    src = data['src']
    dest = data['dest']

    body = data['body']
    incoming_message_id = body['msg_id']
    type = body['type']

    if type == 'init':

        state['node_id'] = body['node_id']
        state['node_ids'] = body['node_ids']
        
        response = {
            "src": state['node_id'],
            "dest": src,
            "body": {
                "type": "init_ok",
                "in_reply_to": incoming_message_id
            }
        }
        
        state['outgoing_message_id'] += 1

        json_response = json.dumps(response)
        print("{}\n".format(json_response))
        return json_response


    if type == 'echo':
        response = {
            "src": state['node_id'],
            "dest": src,
            "body": {
                "type": "echo_ok",
                "msg_id": state['outgoing_message_id'],
                "echo": body['echo'],
                "in_reply_to": incoming_message_id
            }
        }
        
        state['outgoing_message_id'] += 1
        print("{}\n".format(json.dumps(response)))


if __name__ == '__main__':
    while True:
        jsondata = ""
        for line in iter(sys.stdin.readline, "\n"):
            buffer.append(line)
            continue
        
        jsondata = "".join(buffer)
        buffer = []
        work(jsondata, state)